Hacktoberfest - Theme Switcher
1VinceP/vue-simple-notes pull request #26
Opened 2020-10-13 23:15 UTC by astnrgn

Updated app to have a theme switcher button, going between light and dark, at the top right of the app. Elements that were previously dark have been updated to adjust to white background for light-mode

([Issue](https://github.com/1VinceP/vue-simple-notes/issues/11))

2020-10-14 16:42 UTC, 1VinceP requested changes
Theme switching works great. Some suggestions:
- The textarea is very tiny, and also does not change with the theme
- The "add new note" + button does not have a good hover background for the light theme
- The theme toggle button should have `border-radius: 3px` or be a smaller icon, especially on mobile
- code-style changes, see attached comment

2020-10-14 16:42 UTC, 1VinceP commented on src/App.vue
> +      }"
Rather than using key/value for app, I would prefer the array syntax:
```js
:class="['app', { 'app--light-mode': !darkMode }]"
```
Please make similar adjustments to the other classes

2020-10-14 22:07 UTC, astnrgn commented on src/App.vue
> +      }"
Updated to use array syntax in app where applicable (App, NoteEdit, PreviewControls)

2020-10-14 22:07 UTC, astnrgn commented
> Theme switching works great. Some suggestions:
> 
> * The textarea is very tiny, and also does not change with the theme
  Fixed to have textarea inherit its initial class, and correct stying with theme change

> * The "add new note" + button does not have a good hover background for the light theme
  Updated to have similar color to orange in "New Note" cards with lighter opacity

> * The theme toggle button should have `border-radius: 3px` or be a smaller icon, especially on mobile
    Added border-radius to toggle button on desktop and added two icons for mobile toggling (icons found from https://icons8.com/)

> * code-style changes, see attached comment
   Responded in comment above

2020-10-15 03:45 UTC, 1VinceP approved these changes

2020-10-15 03:46 UTC, 1VinceP commented
Very nice, thank you!

2020-10-15 03:46 UTC, merged